---
name: Check Markdown links
on:
  push:
    paths:
      - "**.md"
  pull_request:
    branches:
      - main
    paths:
      - "**.md"
jobs:
  check-links:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-pr-review
          fail_on_error: true
          config_file: .github/workflows/.linkspector.yml
